spec:
  template:
    spec:
      containers:
        - name: adapter
          volumeMounts:
            - name: ca
              mountPath: /ca
              readOnly: true
      volumes:
        - name: ca
          configMap:
            name: cicd-ca
